### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Screamer-Y** [Limmen/csle#317]
I am new to this repo and I'm interested in its features. So I try to deploy it on my own machine, which is Ubuntu 22.04 meet all the prerequisites.
I follow the [instruction ](https://limmen.dev/csle/docs/installing/) and most of the command works properly, but I still came across some problems:
1. Listing 54: Command to initialize a Docker swarm.
`swarm init --advertise-addr <ip address of the leader>`
It works when I change 'swarm' to 'docker swarm'
2. Listing 60: Commands to insert emulation configurations into the metastore.
The directory is now '030'(I think this is a version?), but the make file still using '020'. After modification it works
3. Listing 69: Commands to install the web application of the CSLE management system.
When doing npm install I met, probably a react problem:
````
Log files:
/home/test/.npm/_logs/2023-10-04T04_49_52_953Z-debug-0.log

\# npm resolution error report

While resolving: csle_mgmt_webapp@0.3.0
Found: react@18.0.0
node_modules/react
  react@"18.0.0" from the root project

Could not resolve dependency:
peer react@"^16.8.1 || ^17" from react-alert@7.0.3
node_modules/react-alert
  react-alert@"^7.0.3" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
````
fix(?) with adding '--legacy-peer-deps'.
4. Listing 15: Lines to add to `pg_hba.conf`; 
I am confused with the IP show in the lines and I change the ip '172.31.212.0' with my own ip. I dont know whether it is correct.
**After all of this, I ran _csle init_, it shows 'Successfully initialized configuration from configuration file: /home/test/csle//config.json'**
Then I ran 'csle ls -all' and occurs the exception:
```
CSLE cluster:
Uncaught exception
Traceback (most recent call last):
  File "/home/test/anaconda3/envs/csle/bin/csle", line 8, in <module>
    sys.exit(commands())
  File "/home/test/anaconda3/envs/csle/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/test/anaconda3/envs/csle/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/test/anaconda3/envs/csle/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/test/anaconda3/envs/csle/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/test/anaconda3/envs/csle/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/test/anaconda3/envs/csle/lib/python3.9/site-packages/csle_cli/cli.py", line 1595, in ls
    list_all(all=all, running=running, stopped=stopped)
  File "/home/test/anaconda3/envs/csle/lib/python3.9/site-packages/csle_cli/cli.py", line 1731, in list_all
    list_cluster()
  File "/home/test/anaconda3/envs/csle/lib/python3.9/site-packages/csle_cli/cli.py", line 2095, in list_cluster
    for node in config.cluster_config.cluster_nodes:
AttributeError: 'NoneType' object has no attribute 'cluster_config'
```
I first went to the config.json in the 'csle' dic and found attrs "metastore_ip" and "cluster_config" with unfamiliar ip like '172.31.212.92', so I change it to my own ip, but it dosent work.
Then I follow the code and found my 'config' table in 'csle' postgres database is totally empty, so I get stucked.
In the end I have two problems:
1. How to fix the error above?
2. I see lots of cluster/worker config in the installing stage, but if I only want to deploy it on a single machine, what should I deal with those config?

**Comment by Limmen** [comment]
Hi @Screamer-Y 

Thank you for your interest in the project. Sorry for the late reply, I missed this issue in my inbox.

1. Regarding Listing 54, yes you are right it should be `docker swarm init`. I will update the docs.
2. Regarding Listing 60, good catch, I fixed it now on Master (we updated to 040 but no major changes to if you got 030 working you don't need to upgrade)
3. Regarding npm. I have had to use --legacy-peer-deps on some machines as well. I will look into it when I have time if I can upgrade react.

Regarding the cluster configuration, it should work with your own IP if you have a single node. Then put that node as a leader.

It looks like your installation is correct except for one part. In cluster.config you have to mark your IP as the leader node. Then if you re-run "csle init" it will create the configuration for you, see:
https://github.com/Limmen/csle/blob/master/simulation-system/libs/csle-cli/src/csle_cli/cli.py#L43

**Comment by Screamer-Y** [comment]
Hi @Limmen ,
Thank you so much for your assistance, and it works. As I mentioned in the last comment I tried config the ip as my own ip in config.json but it didn't work. However it works this time, probably something wrong in the environment previously.

I think the Installation Process works well now. Again I really appreciate your work and can't wait to try it out!

Another thing is that I think it's better to include the configuration of config.json in the installation instruction, it would help.

**Comment by Limmen** [comment]
Great @Screamer-Y, thank you for the feedback.

It is in the plans to setup a devops pipeline with ansible to automate the installation process, right now it is a bit tedious.
