### ISSUE TITLE
Environmental installation

### ISSUE THREAD

**Issue by NNNNelson** [Limmen/csle#332]
I am very interested in your work. Can you create a video to demonstrate the process of installing CLSE.

**Comment by NNNNelson** [comment]
hello,In this step, how do I switch between the leader and worker servers to generate different SSH keys。
![image](https://github.com/Limmen/csle/assets/128298843/09a239b4-8dc5-4ef5-a758-93985fa254ea)

**Comment by Limmen** [comment]
Login with SSH on the servers using the password

**Comment by Limmen** [comment]
Hi @NNNNelson 

Here is a video detailing the installation: https://www.youtube.com/watch?v=l_g3sRJwwhc

It is now automated with Ansible and should be a lot simpler.
