### ISSUE TITLE
Initialization Failure: Unable to Read Configuration File and Connect to PostgreSQL Database

### ISSUE THREAD

**Issue by kingxiaofire** [Limmen/csle#357]
### Problem Description:
Encountered an issue while attempting to initialize the "csle" program. Upon executing the csle init command, the system returned the following error:

### Error message
```
Failed to read configuration file from: /home/USERNAME/csle/config.json. Exception: connection failed: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request., OperationalError('connection failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.')
Uncaught exception
Traceback (most recent call last):
  File "/home/USERNAME/miniconda3/bin/csle", line 5, in <module>
    from csle_cli.cli import commands
  File "/home/USERNAME/miniconda3/lib/python3.9/site-packages/csle_cli/cli.py", line 22, in <module>
    ClusterUtil.get_config()
  File "/home/USERNAME/miniconda3/lib/python3.9/site-packages/csle_common/util/cluster_util.py", line 36, in get_config
    config = MetastoreFacade.get_config(id=1)
  File "/home/USERNAME/miniconda3/lib/python3.9/site-packages/csle_common/metastore/metastore_facade.py", line 3868, in get_config
    with psycopg.connect(f"{constants.METADATA_STORE.DB_NAME_PROPERTY}={constants.METADATA_STORE.DBNAME} "
  File "/home/USERNAME/miniconda3/lib/python3.9/site-packages/psycopg/connection.py", line 727, in connect
    raise ex.with_traceback(None)
psycopg.OperationalError: connection failed: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```
     
### Installation Information
Installation method: manual installation,
OS：Ubuntu 22.04

### Questions
In fact, there was also an issue of not being able to connect to the database during automatic installation.

Additionally, I would appreciate it if you could provide comments on the configuration information in the csle/config.json file. I cannot distinguish what these users are used for, such as "metastore_user": "csle", "metastore_password": "csle", and the default user “postgres” for postgreSQL, as well as the “csle” user for postgreSQL. Which user was used during the installation process to connect to the database? Where is the code for the connection written? Thank you so much.

**Comment by Limmen** [comment]
Hi @kingxiaofire ,

Is this path "/home/USERNAME/csle/config.json" correct? It seems that csle could not find the config file. It should be placed at $CSLE_HOME/config.json. 

"metastore_user" is the user to use for the Postgres database. "metastore_password" is the password to connect to the database. See: https://github.com/Limmen/csle/blob/master/simulation-system/libs/csle-common/src/csle_common/metastore/metastore_facade.py#L100

During the installation process (i.e., Ansible) it uses the postgres user and password to connect to the PostgreSQL server and create the csle user and the csle database. Then after installation, it will connect to the database using the csle-user.

**Comment by Limmen** [comment]
Good catch, the newline should be removed. Do you want to open a PR and fix it? Otherwise I will do it when I have time.

You are correct about the constants.py file and you can always edit the constants manually to get the desired behavior. Note however that if CSLE is installed correctly then it should read the config.json file and automatically update constants.py. See:

https://github.com/Limmen/csle/blob/master/simulation-system/libs/csle-cli/src/csle_cli/cli.py#L24
https://github.com/Limmen/csle/blob/master/simulation-system/libs/csle-common/src/csle_common/util/cluster_util.py#L54
