### ISSUE TITLE
Need configuration to run Intrusion Response Game simulation

### ISSUE THREAD

**Issue by amir-coder** [Limmen/csle#359]
Hi, I'm trying to use the Intrusion Response Game, I need config json file and I don't know where to find it

```
# init LocalIntrusionResponseGameConfig

local_intrusion_response_game_config = None
# init IntrusionResponseGameLocalPOMDPDefenderConfig

config = IntrusionResponseGameLocalPOMDPDefenderConfig(env_name = "intrusion_response_game_local_pomdp_defender", local_intrusion_response_game_config= local_intrusion_response_game_config,
                 attacker_strategy = None, defender_strategy = None)

# init IntrusionResponseGameLocalPOMDPDefenderEnv

env = IntrusionResponseGameLocalPOMDPDefenderEnv(config = config) 
```

**Comment by Limmen** [comment]
What error do you get when you run the code that you pasted? It looks correct to me. 

If you want to start our with a simpler game then the stopping game is more suitable, there are several examples in the examples folder.

**Comment by amir-coder** [comment]
Hi, 
I need a json file configuration to create an instanse of the class `LocalIntrusionResponseGameConfig` by using `.from_json_file` abstract method, is there any configuration available?

**Comment by Limmen** [comment]
I see, then probably you have not installed the entire CSLE platform. 

You can find example configurations at: https://github.com/Limmen/csle/blob/master/simulation-system/envs/local_intrusion_response_pomdp_attacker/config_v_001.py#L386 which you then can call .to_json_file(path) on to get the json.

**Comment by Limmen** [comment]
Try following one of the examples and then you can modify as needed.

E.g. https://github.com/Limmen/csle/blob/master/examples/training/ppo/local_intrusion_response_pomdp_defender/run_vs_random_attacker_v_001.py#L149
