### ISSUE TITLE
Setting up csle on 1 machine only

### ISSUE THREAD

**Issue by amir-coder** [Limmen/csle#361]
Hello, I trying to setup csle on my local machine (1 server) and I got confused in the step of seting 1 Leader and 1 worker in the cluster, how do I set up csle in the case where I have 1 machine only.

**Comment by Limmen** [comment]
Hi @amir-coder , you can set it up with just one machine, then that machine will be the leader and you do not have any workers.

**Comment by amir-coder** [comment]
hello @Limmen, thank you, but I recieved this error when I didnt specify any workers:

TASK [Add workers to create_cluster.sql file] *************************************************************************************************************************************************
fatal: [10.236.182.220]: FAILED! => {"msg": "'dict object' has no attribute 'worker'. 'dict object' has no attribute 'worker'"}

**Comment by Limmen** [comment]
To specify no workers keep it as an empty list but do not remove the list completely

**Comment by Limmen** [comment]
Great! @amir-coder
