### ISSUE TITLE
POMDP defender simulation observation is [L, belief] instead of [Severe IDS alerts, Warning IDS alerts, Login attempts]

### ISSUE THREAD

**Issue by amir-coder** [Limmen/csle#370]
Hi, I'm trying to get the observation from the environment and train t-spsa with poisoning attacks that modify the observation value, in the [readme file](https://github.com/Limmen/csle/tree/master/simulation-system/envs/stopping_pomdp_defender#readme) it's mentioned that the observation is  [Severe IDS alerts, Warning IDS alerts, Login attempts] while the gym environment `gym.make("csle-stopping-pomdp-defender-003", config=config)` step method returns a 2 value vector observation containing L stops remaining and a belief value. I want to understand how to configure that.

**Comment by Limmen** [comment]
The belief is a sufficient statistic of the alerts so you do not need them. We have updated the code since we wrote that paper in 2021.

**Comment by Limmen** [comment]
See this paper for more updated details: https://ieeexplore.ieee.org/document/10175554

**Comment by amir-coder** [comment]
Hello again @Limmen, thank you for pointing out to your paper. While still trying to reproduce your results in the paper you shared, I got unexpected results:

I'm using: 
- emulation "csle-level9-060"
- simulation 'csle-stopping-pomdp-defender-006'
- statistics dataset from the release # 4 https://github.com/Limmen/csle/releases/tag/v0.4.0 statistics_dataset_14_nov_22_json
- for the reward tensor I'm using: R_INT=-5, R_COST=-2, R_SLA=2, R_ST=30
- I'm using T-SPSA
![intrusion_length](https://github.com/Limmen/csle/assets/56568152/a904bc7a-9dce-4a45-9226-863f531fd4d7)
![return](https://github.com/Limmen/csle/assets/56568152/905defcc-fc66-44ff-a5cb-3d9421265b6c)

- for 1000 episodes, return and intrusion length didn't converge properly. I wonder if there is any mistake in setting up the environment and I didn't find in your paper the reward you used for training.

**Comment by Limmen** [comment]
Good work @amir-coder 

T-SPSA is notoriously unstable unfortunately, you have to tune these parameters: https://github.com/Limmen/csle/blob/master/examples/training/t_spsa/stopping_pomdp_defender/run_vs_random_attacker_v_001.py#L30

Mainly the parameters c and A. 

For more stable convergence, consider CEM, PPO or Differetial evolution (DE).

**Comment by amir-coder** [comment]
Thank you, I switched to using PPO and I'm satisfied with it's convergence so far. I appreciate your help
